# TCL File Generated by Component Editor 11.1sp2
# Fri Nov 27 11:49:20 CET 2020
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_gestion_anemo "avalon_gestion_anemo" v1.0
# | LS 2020.11.27.11:49:20
# | circuit gestion anemo
# | 
# | C:/Users/Xavi/Documents/FPGA2020/GITDOCS/SOPC_BE_Q11MODIF/avalon_gestion_anemo.vhd
# | 
# |    ./avalon_gestion_anemo.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalon_gestion_anemo
# | 
set_module_property DESCRIPTION "circuit gestion anemo"
set_module_property NAME avalon_gestion_anemo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Other
set_module_property AUTHOR LS
set_module_property DISPLAY_NAME avalon_gestion_anemo
set_module_property TOP_LEVEL_HDL_FILE avalon_gestion_anemo.vhd
set_module_property TOP_LEVEL_HDL_MODULE avalon_gestion_anemo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME avalon_gestion_anemo
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalon_gestion_anemo.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 address address Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end in_freq_anemometre export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_1
# | 
add_interface conduit_end_1 conduit end

set_interface_property conduit_end_1 ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_2
# | 
add_interface conduit_end_2 conduit end

set_interface_property conduit_end_2 ENABLED true

add_interface_port conduit_end_2 data_valid export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_3
# | 
add_interface conduit_end_3 conduit end

set_interface_property conduit_end_3 ENABLED true

add_interface_port conduit_end_3 data_anemometre export Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_4
# | 
add_interface conduit_end_4 conduit end

set_interface_property conduit_end_4 ENABLED true

add_interface_port conduit_end_4 AffCentaine export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_5
# | 
add_interface conduit_end_5 conduit end

set_interface_property conduit_end_5 ENABLED true

add_interface_port conduit_end_5 AffDizane export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_6
# | 
add_interface conduit_end_6 conduit end

set_interface_property conduit_end_6 ENABLED true

add_interface_port conduit_end_6 AffUnite export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_7
# | 
add_interface conduit_end_7 conduit end

set_interface_property conduit_end_7 ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_8
# | 
add_interface conduit_end_8 conduit end

set_interface_property conduit_end_8 ENABLED true

add_interface_port conduit_end_8 leds_config export Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_9
# | 
add_interface conduit_end_9 conduit end

set_interface_property conduit_end_9 ENABLED true

add_interface_port conduit_end_9 BCD7SEGMENT export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_10
# | 
add_interface conduit_end_10 conduit end

set_interface_property conduit_end_10 ENABLED true

add_interface_port conduit_end_10 multiplex export Output 3
# | 
# +-----------------------------------
